# Generated by Django 3.2 on 2021-05-05 04:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_followers_following'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='following',
            new_name='follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following_username',
            new_name='follow',
        ),
        migrations.DeleteModel(
            name='followers',
        ),
    ]
