# Generated by Django 3.2.1 on 2021-05-09 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_photo_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32)),
                ('view_count', models.BigIntegerField(default=1)),
                ('like_count', models.BigIntegerField(default=1)),
                ('comment_count', models.BigIntegerField(default=1)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
