# Generated by Django 3.2.1 on 2021-05-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_recommender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommender',
            name='id',
        ),
        migrations.AlterField(
            model_name='recommender',
            name='comment_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='tag',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
