# Generated by Django 3.2.1 on 2021-05-10 02:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('1', 'following'), ('2', 'likememe'), ('3', 'commentmeme'), ('4', 'alsocomment'), ('5', 'likecomment')], max_length=32)),
                ('message', models.TextField()),
                ('url', models.URLField()),
                ('read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
